[package]
name = "scnrtest"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo = "0.84.0"
clap = { version = "4.5.23", features = ["derive", "cargo"] }
env_logger = "0.11"
scnr = { version = "0.6.0", path = "../scnr" }
serde_json = "1.0.133"

[profile.release]
opt-level = 3
lto = true
debug = true
